{
 "title": "Prometheus Kafka Exporter",
 "description": "Kafka resource usage and throughput",
 "tags": [ "kafka" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_consumergroup_current_offset, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_consumergroup_current_offset{job=~\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_topic_partition_current_offset{instance='$instance',topic!='__consumer_offsets',topic!='--kafka'}, topic)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aws_kafka_data_logs_disk_used_average,dimension_Cluster_Name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=~\"$instance\",topic=~\"$topic\"}[5m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=\"$instance\",topic=~\"$topic\"}) by (consumergroup, topic) ",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance', topic=~\"$topic\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance',topic=~\"$topic\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "timeseries",
   "description": "Average disk usage (%) per broker for MSK cluster p-hk-msk-kafka-02 in ap-east-1",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_kafka_data_logs_disk_used_average{dimension_Cluster_Name=~\"$cluster\", dimension_Broker_ID!=\"\"}",
     "legendFormat": "Broker {{ dimension_Broker_ID }}"
    },
    {
     "expr": "aws_kafka_data_logs_disk_used_average{dimension_Cluster_Name=~\"$cluster\", dimension_Broker_ID=\"\"}",
     "legendFormat": "{{dimension_Cluster_Name}}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{instance=\"$instance\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}