{
 "title": "YACE - AWS NetworkELB",
 "tags": [
  "aws",
  "networkelb"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_average,region)"
    }
   },
   {
    "name": "loadbalancer",
    "label": "LoadBalancer",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_average{region=\"$region\"},dimension_LoadBalancer)"
    }
   },
   {
    "name": "targetgroup",
    "label": "TargetGroup",
    "query": {
     "query": "label_values(aws_networkelb_healthy_host_count_average{dimension_LoadBalancer=\"$loadbalancer\"},dimension_TargetGroup)"
    }
   },
   {
    "name": "scheme",
    "label": "Scheme",
    "query": {
     "query": "label_values(aws_networkelb_active_flow_count_average{dimension_LoadBalancer=\"$loadbalancer\"},tag_service_k8s_aws_stack)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Flow Count (Average, 1m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_average{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}"
    }
   ]
  },
  {
   "title": "New Flow Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_networkelb_new_flow_count_sum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}"
    }
   ]
  },
  {
   "title": "Healthy Host Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_networkelb_healthy_host_count_minimum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\",dimension_TargetGroup=~\"$targetgroup\"}",
     "legendFormat": "{{dimension_TargetGroup}}"
    }
   ]
  },
  {
   "title": "Consumed LCUs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aws_networkelb_consumed_lcus_average{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Active Flow Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_active_flow_count_average{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}} - Average"
    },
    {
     "expr": "aws_networkelb_active_flow_count_maximum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}} - Max"
    }
   ]
  },
  {
   "title": "New Flow Count Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "aws_networkelb_new_flow_count_sum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Peak Bytes Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "aws_networkelb_peak_bytes_per_second_maximum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  {
   "title": "Peak Packets Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "aws_networkelb_peak_packets_per_second_maximum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}}"
    }
   ]
  },
  { "title": "Reset", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "TCP Reset Count Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_tcp_client_reset_count_sum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}",
     "legendFormat": "{{dimension_LoadBalancer}} - Client Reset"
    },
    {
     "expr": "rate(aws_networkelb_tcp_elb_reset_count_sum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}[5m]) * 60",
     "legendFormat": "{{dimension_LoadBalancer}} - ELB Reset"
    },
    {
     "expr": "rate(aws_networkelb_tcp_target_reset_count_sum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\"}[5m]) * 60",
     "legendFormat": "{{dimension_LoadBalancer}} - Target Reset"
    }
   ]
  },
  { "title": "Health Check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Healthy/Unhealth Host Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_networkelb_healthy_host_count_minimum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\",dimension_TargetGroup=~\"$targetgroup\"}",
     "legendFormat": "{{dimension_TargetGroup}} - Health"
    },
    {
     "expr": "aws_networkelb_un_healthy_host_count_maximum{region=~\"$region\",dimension_LoadBalancer=~\"$loadbalancer\",dimension_TargetGroup=~\"$targetgroup\"}",
     "legendFormat": "{{dimension_TargetGroup}} - Unhealth"
    }
   ]
  }
 ]
}